vars:
  ansible_python_interpreter=python3.9

plugin: azure.azcollection.azure_rm
cloud_environment: AzureCloud
include_vm_resource_groups:
  - pers-robin_mohan-rg
auth_source: env
ad_user: robin
keyed_groups:
  - prefix: tag
    key: tags