vars:
  ansible_python_interpreter: python3

plugin: azure.azcollection.azure_rm
cloud_environment: AzureCloud
include_vm_resource_groups:
  - pers-robin_mohan-rg
auth_source: cli
ad_user: robin
keyed_groups:
  - prefix: tag
    key: tags